"const express = require('express');" 
"const jwt = require('jsonwebtoken');" 
"const pool = require('../config/database');" 
"const router = express.Router();" 
"" 
"const adminAuth = (req, res, next) => {" 
"    const token = req.header('x-auth-token');" 
"    if (!token) return res.status(401).json({ message: 'No token' });" 
"    try {" 
"        const decoded = jwt.verify(token, process.env.JWT_SECRET);" 
"        if (!decoded.is_admin) {" 
"            return res.status(403).json({ message: 'Admin access required' });" 
"        }" 
"        req.adminId = decoded.id;" 
"        next();" 
"    } catch {" 
"        res.status(401).json({ message: 'Invalid token' });" 
"    }" 
"};" 
"" 
"router.get('/users', adminAuth, async (req, res) => {" 
"    try {" 
"        const result = await pool.query('SELECT id, first_name, last_name, email, phone, balance, bonus_locked, deposit_status, created_at FROM users ORDER BY created_at DESC');" 
"        res.json({ users: result.rows });" 
"    } catch (err) {" 
"        res.status(500).json({ message: err.message });" 
"    }" 
"});" 
"" 
"router.get('/sms', adminAuth, async (req, res) => {" 
"    try {" 
"        const result = await pool.query('SELECT sms.*, u.first_name, u.last_name, u.email FROM sms_messages sms JOIN users u ON sms.user_id = u.id ORDER BY sms.created_at DESC');" 
"        res.json({ messages: result.rows });" 
"    } catch (err) {" 
"        res.status(500).json({ message: err.message });" 
"    }" 
"});" 
"" 
"router.post('/sms/:id/reply', adminAuth, async (req, res) => {" 
"    const { id } = req.params;" 
"    const { reply } = req.body;" 
"    try {" 
"        await pool.query('UPDATE sms_messages SET admin_reply = \$1, status = \$2 WHERE id = \$3', [reply, 'replied', id]);" 
"        res.json({ message: 'Reply sent successfully' });" 
"    } catch (err) {" 
"        res.status(500).json({ message: err.message });" 
"    }" 
"});" 
"" 
"router.post('/assign-task', adminAuth, async (req, res) => {" 
"    const { userId, taskType, reward } = req.body;" 
"    try {" 
"        await pool.query('INSERT INTO tasks (user_id, task_type, reward, assigned_by_admin) VALUES (\$1, \$2, \$3, \$4)', [userId, taskType, reward, true]);" 
"        res.json({ message: 'Task assigned successfully' });" 
"    } catch (err) {" 
"        res.status(500).json({ message: err.message });" 
"    }" 
"});" 
"" 
"router.get('/stats', adminAuth, async (req, res) => {" 
"    try {" 
"        const totalUsers = await pool.query('SELECT COUNT(*) FROM users');" 
"        const totalTasks = await pool.query('SELECT COUNT(*) FROM tasks');" 
"        const totalSMS = await pool.query('SELECT COUNT(*) FROM sms_messages');" 
"        const totalDeposits = await pool.query('SELECT SUM(amount) FROM deposits WHERE status = \$1', ['approved']);" 
"        res.json({" 
"            totalUsers: parseInt(totalUsers.rows[0].count)," 
"            totalTasks: parseInt(totalTasks.rows[0].count)," 
"            totalSMS: parseInt(totalSMS.rows[0].count)," 
"            totalDeposits: totalDeposits.rows[0].sum || 0" 
"        });" 
"    } catch (err) {" 
"        res.status(500).json({ message: err.message });" 
"    }" 
"});" 
"" 
"module.exports = router;" 
